project:
  type: website
  output-dir: docs

website:
  title: "Lin611 - Spring 2023"
  navbar:
    left:
      - href: syllabus.qmd
        text: "Syllabus"
      - href: schedule.qmd
        text: "Schedule"
      - href: class_notes.qmd
        text: "Class Notes"
    right:
      - icon: github
        href: "https://classroom.github.com/classrooms/121321157-lin611-2023"
  sidebar: 
    # - title: "Home"
    #   style: "floating"
    - title: "Class Notes"
      href: class_notes.qmd
      style: "floating"
      search: true
      contents: class_notes/
    - title: "About"
      href: about.qmd
      style: floating
      contents: 
        - about.qmd
        - schedule.qmd
  page-navigation: true
  favicon: assets/logo.png
  twitter-card: 
    image: assets/logo2.png
  open-graph:
    image: assets/logo2.png
  
format:
  html:
    theme: darkly
    css: styles.css
    license: "CC-BY-SA 4.0"
    smooth-scroll: true
    link-external-newwindow: true
    include-in-header: google_font.html
    mainfont: "Atkinson Hyperlegible"
    code-link: true
  pdf:
    license: "CC-BY-SA 4.0"

editor: visual

