project:
  type: website

website:
  title: "Lin611 - Spring 2023"
  navbar:
    left:
      - href: syllabus.qmd
        text: "Syllabus"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: darkly
    css: styles.css
    license: "CC-BY-SA 4.0"

editor: visual

