---
title: "Schedule"
page-layout: full
format: html
---

The topics and readings listed here are the tentative schedule for the course. We may find, in the room, that some topics will take longer than initially scheduled.

+----------------+----------------+---------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| Week           | Dates          | Topics                                            | Readings                                                                                                      | Supplementary Resources                                                                                                                | Notes                         |
+===============:+================+===================================================+===============================================================================================================+========================================================================================================================================+===============================+
| 1              | Jan 10,12      | Onboarding                                        | [Github Onboarding with RStudio](https://jofrhwld.github.io/blog/posts/2022/12/2022-12-21_github-onboarding/) | [R4DS: RMarkdown](https://r4ds.had.co.nz/r-markdown.html)                                                                              |                               |
|                |                |                                                   |                                                                                                               |                                                                                                                                        |                               |
|                |                |                                                   |                                                                                                               | [Quarto Tutorial: Hello Quarto](https://quarto.org/docs/get-started/hello/rstudio.html)                                                |                               |
|                |                |                                                   |                                                                                                               |                                                                                                                                        |                               |
|                |                |                                                   |                                                                                                               | [Quarto Tutorial: Computations](https://quarto.org/docs/get-started/computations/rstudio.html)                                         |                               |
|                |                |                                                   |                                                                                                               |                                                                                                                                        |                               |
|                |                |                                                   |                                                                                                               | [Quarto Tutorial: Authoring](https://quarto.org/docs/get-started/authoring/rstudio.html)                                               |                               |
+----------------+----------------+---------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| 2              | Jan 17, 19     | Introduction to R                                 | Winter, Ch 1                                                                                                  | [Hands-On Programming with R, Chapter 2](https://rstudio-education.github.io/hopr/basics.html)                                         | Chapter 1 blog due Friday     |
|                |                |                                                   |                                                                                                               |                                                                                                                                        |                               |
|                |                |                                                   |                                                                                                               | [2017 LSA Course: Introduction to R](https://jofrhwld.github.io/teaching/courses/2017_lsa/lectures/Session_1.nb.html)                  |                               |
+----------------+----------------+---------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| 3              | Jan 24, 26     | Tidyverse and Workflows                           | Winter, Ch 2                                                                                                  | [R4DS, Tidy Data](https://r4ds.had.co.nz/tidy-data.html)                                                                               |                               |
|                |                |                                                   |                                                                                                               |                                                                                                                                        |                               |
|                |                |                                                   |                                                                                                               | [R4DS, Data-visualization](https://r4ds.had.co.nz/data-visualisation.html)                                                             |                               |
|                |                |                                                   |                                                                                                               |                                                                                                                                        |                               |
|                |                |                                                   |                                                                                                               | [2017 LSA Course: Data Frames](https://jofrhwld.github.io/teaching/courses/2017_lsa/lectures/Session_2.nb.html)                        |                               |
|                |                |                                                   |                                                                                                               |                                                                                                                                        |                               |
|                |                |                                                   |                                                                                                               | [2017 LSA Course: Split-Apply-Combine](https://jofrhwld.github.io/teaching/courses/2017_lsa/lectures/Session_3.nb.html)                |                               |
|                |                |                                                   |                                                                                                               |                                                                                                                                        |                               |
|                |                |                                                   |                                                                                                               | [2017 LSA Course: ggplot2](https://jofrhwld.github.io/teaching/courses/2017_lsa/lectures/Session_4.nb.html)                            |                               |
|                |                |                                                   |                                                                                                               |                                                                                                                                        |                               |
|                |                |                                                   |                                                                                                               | [tidyr cheat sheet (pdf)](https://posit.co/wp-content/uploads/2022/10/tidyr.pdf)                                                       |                               |
|                |                |                                                   |                                                                                                               |                                                                                                                                        |                               |
|                |                |                                                   |                                                                                                               | [dplyr cheat sheet (pdf)](https://posit.co/wp-content/uploads/2022/10/data-transformation-1.pdf)                                       |                               |
|                |                |                                                   |                                                                                                               |                                                                                                                                        |                               |
|                |                |                                                   |                                                                                                               | [ggplot2 cheat sheet (pdf)](https://posit.co/wp-content/uploads/2022/10/data-visualization-1.pdf)                                      |                               |
+----------------+----------------+---------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| 4              | Jan 31, Feb 02 | Tidyverse and Workflows (part 2)                  | Winter, Ch 2                                                                                                  |                                                                                                                                        | Chapter 2 blog due Friday     |
+----------------+----------------+---------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| 5              | Feb 07, 09     | Descriptive Statistics, Models, and Distributions | Winter, Ch3                                                                                                   | [R4DS, Exploratory Data Analysis](https://r4ds.had.co.nz/exploratory-data-analysis.html)                                               | Chapter 3 blog due Friday     |
+----------------+----------------+---------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| 6              | Feb 14, 16     | Intro to Linear Models                            | Winter Ch4                                                                                                    | [R4DS: Model Basics](https://r4ds.had.co.nz/model-basics.html)                                                                         | Chapter 4 blog due Friday     |
|                |                |                                                   |                                                                                                               |                                                                                                                                        |                               |
|                |                |                                                   |                                                                                                               | [2017 LSA Course: Fitting Linear Models](https://jofrhwld.github.io/teaching/courses/2017_lsa/lectures/Session_5.nb.html)              |                               |
+----------------+----------------+---------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| 7              | Feb 21, 23     | Correlations and Transformations                  | Winter Ch5                                                                                                    | [R4DS: Model Basics](https://r4ds.had.co.nz/model-basics.html)                                                                         | Chapter 5 blog due Friday     |
|                |                |                                                   |                                                                                                               |                                                                                                                                        |                               |
|                |                |                                                   |                                                                                                               | [2017 LSA Course: Fitting Linear Models](https://jofrhwld.github.io/teaching/courses/2017_lsa/lectures/Session_5.nb.html)              |                               |
+----------------+----------------+---------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| 8              | Feb 28, Mar 02 | Multiple Regression                               | Winter Ch6                                                                                                    | [R4DS: Model Basics](https://r4ds.had.co.nz/model-basics.html)                                                                         | Chapter 6 blog due Friday     |
|                |                |                                                   |                                                                                                               |                                                                                                                                        |                               |
|                |                |                                                   |                                                                                                               | [2017 LSA Course: Fitting Linear Models](https://jofrhwld.github.io/teaching/courses/2017_lsa/lectures/Session_5.nb.html)              |                               |
+----------------+----------------+---------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| 9              | Mar 07, 09     | Categorical Predictors                            | Winter Ch7                                                                                                    | [forcats cheat sheet (pdf)](https://posit.co/wp-content/uploads/2022/10/factors-1.pdf)                                                 | Chapter 7 blog due Friday     |
|                |                |                                                   |                                                                                                               |                                                                                                                                        |                               |
|                |                |                                                   |                                                                                                               |                                                                                                                                        | **Midterm Project Due**       |
+----------------+----------------+---------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| *Spring Break* | *Mar 14, 16*   | *No class*                                        | *No Class*                                                                                                    |                                                                                                                                        |                               |
+----------------+----------------+---------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| 10             | Mar 21, 23     | Interactions and Non-Linear Effects               | Winter Ch 8                                                                                                   | [Sóskuthy (2017)](https://arxiv.org/abs/1703.05339)                                                                                    | Chapter 8 blog due Friday     |
+----------------+----------------+---------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| 11             | Mar 28, 30     | Inferential Statistics                            | Winter Ch 9,10                                                                                                | Winter Ch 11                                                                                                                           | Chapter 9, 10 blog due Friday |
|                |                |                                                   |                                                                                                               |                                                                                                                                        |                               |
|                |                |                                                   |                                                                                                               | [Visualizing Cohen's *d*](https://rpsychologist.com/cohend/)                                                                           |                               |
|                |                |                                                   |                                                                                                               |                                                                                                                                        |                               |
|                |                |                                                   |                                                                                                               | [Kirby & Sonderegger (2018)](https://doi.org/10.1016/j.wocn.2018.05.005)                                                               |                               |
+----------------+----------------+---------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| 12             | Apr 04, 06     | Mixed Models                                      | Winter Ch 14                                                                                                  | [2017 LSA Course: Mixed Effects Models](https://jofrhwld.github.io/teaching/courses/2017_lsa/lectures/Session_7.nb.html)               | Chapter 14 blog due Friday    |
+----------------+----------------+---------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| 13             | Apr 11, 13     | Mixed Models                                      | Winter Ch 15                                                                                                  | [2017 LSA Course: Model Comparison and Bootstrapping](https://jofrhwld.github.io/teaching/courses/2017_lsa/lectures/Session_8.nb.html) | Chapter 15 blog due Friday    |
+----------------+----------------+---------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| 14             | Apr 18, 20     | Generalized Linear Models                         | Winter Ch 12                                                                                                  | Winter Ch 13                                                                                                                           | Chapter 12 blog due Friday    |
+----------------+----------------+---------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| 15             | Apr 25         | Review & Outlook                                  |                                                                                                               | Winter Ch 16                                                                                                                           |                               |
+----------------+----------------+---------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| *Finals*       | *May 04*       |                                                   |                                                                                                               |                                                                                                                                        | Final Project Due             |
+----------------+----------------+---------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
