---
title: "Distributions"
date: 2023-02-07
---

```{r}
#| eval: false
install.packages("droll")
```

```{r}
library(droll)
library(tidyverse)
theme_set(
  theme_bw()
)
```

Simulating 100 groups rolling a d6 10 times

```{r}
set.seed(611)

nsim <- 1000

roll_sims <- 
  tibble(
    sim = seq(1,nsim)
  ) |> 
  ## This will simulate 10 rolls of a d6,
  ## once per simulation.
  mutate(
    rolls = map(
      sim, \(x) rroll(10, d6)
    )
  ) |> 
  ## This counts how many times 1 and 6
  ## came up in each simulation
  mutate(
    one_and_six = map_dbl(
      rolls, \(r)sum(r %in% c(1, 6))
    )
  ) 

roll_sims |> 
  ggplot(aes(one_and_six))+
    stat_bin(binwidth = 1)+
    scale_x_continuous(
      breaks = c(0,5,10)
    )+
    expand_limits(x=c(0,10))
```

Getting the *theoretical* distribution

```{r}
tibble(
  one_and_six = seq(0, 10),
  prob = dbinom(
    one_and_six, 
    size = 10,
    prob = 2/6
  ),
  n = prob * 1000
) |> 
  ggplot(aes(one_and_six, n))+
    geom_col()+
    scale_x_continuous(
      breaks = c(0,5,10)
    )
```
